language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - ADB_INSTALL_TIMEOUT=8

android:
  licenses:
    - "android-sdk-preview-license-.+"
    - "android-sdk-license-.+"
    - "google-gdk-license-.+"

  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug assembleRelease testDebug jacocoFullReport
  - mv build/reports/jacoco/ build/reports/jacoco/
  - mv build/reports/jacoco/jacocoFullReport.xml build/reports/jacoco/jacocoFullReport.xml
  - bash <(curl -s https://codecov.io/bash)

#html {
  #            enabled true
  #            destination file('build/reports/jacoco/html')
  #        }
  #        csv {
  #            enabled true
  #            destination file('build/reports/jacoco/jacocoFullReport.csv')
  #        }
  #        xml{
  #            enabled true
  #            description file('build/reports/jacoco/xml')
  #        }
